add edge cases to create_swapfile script

diff --git a/meta-honeycomb/recipes-honeycomb/swapfile/files/create_swapfile b/meta-honeycomb/recipes-honeycomb/swapfile/files/create_swapfile
--- a/meta-honeycomb/recipes-honeycomb/swapfile/files/create_swapfile
+++ b/meta-honeycomb/recipes-honeycomb/swapfile/files/create_swapfile
@@ -1,19 +1,64 @@
 #!/bin/sh
 #
-# Create 1GB swap file /var/swap
+# Create swap file $SWAP_F.
+# User can choose between 1GB, 2GB, 3GB and 4GB.
 # Activate it and add it to /etc/fstab
 
-# Create swap file
-echo "Creating /var/swap with dd."
-echo "This might take a while, be patient."
-dd if=/dev/urandom of=/var/swap bs=1024 count=1048576
-chmod 600 /var/swap
+SWAP_F=/var/swap
 
-# Enable swap file
-echo "Enabling /var/swap as swap file"
-mkswap /var/swap
-swapon /var/swap
+Help()
+{
+	echo "create_swapfile: creates $SWAP_F swap file."
+	echo "Syntax: create_swapfile n"
+	echo "options:"
+	echo "n     swap file size (in GB). Choose between 1, 2, 3 and 4."
+	echo
+}
 
-# Add to fstab
-echo "Adding /var/swap entry to /etc/fstab so it's persistent to reboot"
-echo "/var/swap   none    swap    sw    0   0" | tee /etc/fstab -a
+while getopts ":h" option; do
+	case $option in
+		h)
+			Help
+			exit;;
+		\?)
+			echo "Error: Invalid option"
+			exit;;
+	esac
+done
+
+if ! [[ "$1" =~ ^[1-4]+$ ]]
+    then
+        echo "Error: only integers between 1 and 4."
+	Help
+	exit 1
+fi
+
+SWAP_SIZE=$(( $1 * 1048576))
+
+# Create $SWAP_F if it doesn't already exist
+if test -f "$SWAP_F"; then
+	echo "$SWAP_F already exists!"
+else
+	echo "Creating /var/swap with dd."
+	echo "This might take a while, be patient."
+	dd if=/dev/urandom of=$SWAP_F bs=1024 count="$SWAP_SIZE"
+	chmod 600 $SWAP_F
+fi
+
+# Enable $SWAP_F if it's not already enabled
+if [[ $(swapon -s | grep "$SWAP_F") ]]; then
+	echo "$SWAP_F is already enabled as swap."
+else
+	echo "Enabling $SWAP_F as swap file."
+	mkswap $SWAP_F
+	swapon $SWAP_F
+fi
+
+# Add $SWAP_F to fstab if it doesn't already exist
+if [[ $(cat /etc/fstab | grep "$SWAP_F") ]]; then
+	echo "$SWAP_F entry already exists in /etc/fstab."
+else
+	echo "Adding $SWAP_F entry to /etc/fstab so it's persistent to reboot"
+	echo "$SWAP_F   none    swap    sw    0   0" | tee /etc/fstab -a
+fi
+
