match hornet .deb with goreleaser

diff --git a/meta-tangle/recipes-iota/hornet/files/hornet_update_snapshot b/meta-tangle/recipes-iota/hornet/files/hornet_update_snapshot
--- a/meta-tangle/recipes-iota/hornet/files/hornet_update_snapshot
+++ b/meta-tangle/recipes-iota/hornet/files/hornet_update_snapshot
@@ -1,8 +1,19 @@
 #!/bin/bash
 
-SNAPSHOT_DIR=/var/lib/hornet/snapshot
+# Set default if none set.
+REMOTE_FILE="${1:-https://dbfiles.iota.org/mainnet/hornet/latest-export.gz.bin}"
+
 echo "Removing current local snapshot."
 rm -f $SNAPSHOT_DIR/latest-export.gz.bin
 
-echo "Downloading latest snapshot."
-wget -P $SNAPSHOT_DIR https://ls.manapotion.io/latest-export.gz.bin
+# Download with timestamping (only download if remote file is newer)
+echo "Checking for the latest snapshot file..."
+echo "This may take a while"
+
+# Capture only stderr
+WGET_STDERR=$( { wget -N "${REMOTE_FILE}"; } 2>&1 >/dev/null )
+if [ $? -ne 0 ]
+then
+    >&2 echo -e "Downloading latest snapshot file failed:\n${WGET_STDERR}\n"
+    exit 1
+fi
